### ISSUE TITLE
Support "id_token token" Response Type to Retrieve Application API Token

### ISSUE THREAD

**Issue by davewoodward** [salte-io/salte-auth-angularjs#46]
### Description
The "id_token token" response type is unable to equate the access token received to the application API if the application API is exposed over a domain that differs from the application itself; a situation that frequently exists when the application API is exposed through an API Gateway.

**Comment by nick-woodward** [comment]
Upgrading to [`salte-auth` 2.x](https://github.com/salte-io/salte-auth/releases/tag/v2.0.0) should resolve this issue.
