### ISSUE TITLE
Enhance Logout to Support WSO2 Identity Server

### ISSUE THREAD

**Issue by davewoodward** [salte-io/salte-auth-angularjs#47]
### Description
The current library includes an Azure-specific logout capability.  Need to make this more flexible to support WSO2 as well as other OpenID Connect identity providers.

**Comment by nick-woodward** [comment]
Upgrading to [`salte-auth` 2.x](https://github.com/salte-io/salte-auth/releases/tag/v2.0.0) should resolve this issue.
